"""Movie database — add your favourites in Exercise 3 (see EXERCISES.md)."""

MOVIES = [
    {
        "title": "The Shawshank Redemption",
        "genre": "Drama",
        "mood": ["contemplative", "inspiring", "emotional"],
        "duration": 142,
        "rating": 9.3,
        "year": 1994,
    },
    {
        "title": "The Dark Knight",
        "genre": "Action",
        "mood": ["intense", "thrilling", "dark"],
        "duration": 152,
        "rating": 9.0,
        "year": 2008,
    },
    {
        "title": "Inception",
        "genre": "Sci-Fi",
        "mood": ["mind-bending", "intense", "thrilling"],
        "duration": 148,
        "rating": 8.8,
        "year": 2010,
    },
    {
        "title": "Forrest Gump",
        "genre": "Drama",
        "mood": ["uplifting", "heartwarming", "inspiring"],
        "duration": 142,
        "rating": 8.8,
        "year": 1994,
    },
    {
        "title": "The Grand Budapest Hotel",
        "genre": "Comedy",
        "mood": ["quirky", "lighthearted", "whimsical"],
        "duration": 99,
        "rating": 8.1,
        "year": 2014,
    },
    {
        "title": "Pulp Fiction",
        "genre": "Crime",
        "mood": ["intense", "dark", "entertaining"],
        "duration": 154,
        "rating": 8.9,
        "year": 1994,
    },
    {
        "title": "Spirited Away",
        "genre": "Animation",
        "mood": ["magical", "whimsical", "enchanting"],
        "duration": 125,
        "rating": 8.6,
        "year": 2001,
    },
    {
        "title": "The Notebook",
        "genre": "Romance",
        "mood": ["romantic", "emotional", "heartwarming"],
        "duration": 123,
        "rating": 7.8,
        "year": 2004,
    },
    {
        "title": "The Matrix",
        "genre": "Sci-Fi",
        "mood": ["futuristic", "dystopian", "psychological"],
        "duration": 136,
        "rating": 8.7,
        "year": 1999,
    },
    {
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "genre": "Fantasy",
        "mood": ["epic", "adventure", "magical"],
        "duration": 178,
        "rating": 8.8,
        "year": 2001,
    },
    {
        "title": "Parasite",
        "genre": "Thriller",
        "mood": ["dark", "intense", "thought-provoking"],
        "duration": 132,
        "rating": 8.6,
        "year": 2019,
    },
    {
        "title": "La La Land",
        "genre": "Romance",
        "mood": ["romantic", "uplifting", "whimsical"],
        "duration": 128,
        "rating": 8.0,
        "year": 2016,
    },
    {
        "title": "Mad Max: Fury Road",
        "genre": "Action",
        "mood": ["intense", "thrilling", "adrenaline"],
        "duration": 120,
        "rating": 8.1,
        "year": 2015,
    },
    {
        "title": "Get Out",
        "genre": "Horror",
        "mood": ["suspenseful", "dark", "thought-provoking"],
        "duration": 104,
        "rating": 7.8,
        "year": 2017,
    },
    {
        "title": "Toy Story",
        "genre": "Animation",
        "mood": ["lighthearted", "heartwarming", "funny"],
        "duration": 81,
        "rating": 8.3,
        "year": 1995,
    },
    {
        "title": "The Social Network",
        "genre": "Drama",
        "mood": ["intense", "psychological", "contemplative"],
        "duration": 120,
        "rating": 7.8,
        "year": 2010,
    },
    {
        "title": "Knives Out",
        "genre": "Mystery",
        "mood": ["entertaining", "quirky", "suspenseful"],
        "duration": 130,
        "rating": 7.9,
        "year": 2019,
    },
    {
        "title": "Whiplash",
        "genre": "Drama",
        "mood": ["intense", "inspiring", "psychological"],
        "duration": 106,
        "rating": 8.5,
        "year": 2014,
    },
    {
        "title": "The Princess Bride",
        "genre": "Fantasy",
        "mood": ["adventure", "funny", "heartwarming"],
        "duration": 98,
        "rating": 8.0,
        "year": 1987,
    },
    {
        "title": "Joker",
        "genre": "Crime",
        "mood": ["dark", "psychological", "intense"],
        "duration": 122,
        "rating": 8.4,
        "year": 2019,
    },
    {
        "title": "Inside Out",
        "genre": "Animation",
        "mood": ["emotional", "heartwarming", "lighthearted"],
        "duration": 95,
        "rating": 8.1,
        "year": 2015,
    },
    {
        "title": "Dune",
        "genre": "Sci-Fi",
        "mood": ["epic", "futuristic", "contemplative"],
        "duration": 155,
        "rating": 8.0,
        "year": 2021,
    },
    {
        "title": "Hot Fuzz",
        "genre": "Comedy",
        "mood": ["funny", "entertaining", "thrilling"],
        "duration": 121,
        "rating": 7.8,
        "year": 2007,
    },
    {
        "title": "Arrival",
        "genre": "Sci-Fi",
        "mood": ["contemplative", "emotional", "mind-bending"],
        "duration": 116,
        "rating": 7.9,
        "year": 2016,
    },
    {
        "title": "The Silence of the Lambs",
        "genre": "Horror",
        "mood": ["suspenseful", "dark", "intense"],
        "duration": 118,
        "rating": 8.6,
        "year": 1991,
    },
    {
        "title": "Before Sunrise",
        "genre": "Romance",
        "mood": ["romantic", "contemplative", "lighthearted"],
        "duration": 101,
        "rating": 8.1,
        "year": 1995,
    },
    {
        "title": "Everything Everywhere All at Once",
        "genre": "Sci-Fi",
        "mood": ["mind-bending", "emotional", "entertaining"],
        "duration": 139,
        "rating": 7.8,
        "year": 2022,
    },
    {
        "title": "The Big Lebowski",
        "genre": "Comedy",
        "mood": ["quirky", "funny", "lighthearted"],
        "duration": 117,
        "rating": 8.1,
        "year": 1998,
    },
]
