"""Movie database — add your favourites in Exercise 3 (see EXERCISES.md)."""

MOVIES = [
    {
        "title": "The Shawshank Redemption",
        "genre": "Drama",
        "mood": ["contemplative", "inspiring", "emotional"],
        "duration": 142,
        "rating": 9.3,
        "year": 1994,
    },
    {
        "title": "The Dark Knight",
        "genre": "Action",
        "mood": ["intense", "thrilling", "dark"],
        "duration": 152,
        "rating": 9.0,
        "year": 2008,
    },
    {
        "title": "Inception",
        "genre": "Sci-Fi",
        "mood": ["mind-bending", "intense", "thrilling"],
        "duration": 148,
        "rating": 8.8,
        "year": 2010,
    },
    {
        "title": "Forrest Gump",
        "genre": "Drama",
        "mood": ["uplifting", "heartwarming", "inspiring"],
        "duration": 142,
        "rating": 8.8,
        "year": 1994,
    },
    {
        "title": "The Grand Budapest Hotel",
        "genre": "Comedy",
        "mood": ["quirky", "lighthearted", "whimsical"],
        "duration": 99,
        "rating": 8.1,
        "year": 2014,
    },
    {
        "title": "Pulp Fiction",
        "genre": "Crime",
        "mood": ["intense", "dark", "entertaining"],
        "duration": 154,
        "rating": 8.9,
        "year": 1994,
    },
    {
        "title": "Spirited Away",
        "genre": "Animation",
        "mood": ["magical", "whimsical", "enchanting"],
        "duration": 125,
        "rating": 8.6,
        "year": 2001,
    },
    {
        "title": "The Notebook",
        "genre": "Romance",
        "mood": ["romantic", "emotional", "heartwarming"],
        "duration": 123,
        "rating": 7.8,
        "year": 2004,
    },
    {
        "title": "The Matrix",
        "genre": "Sci-Fi",
        "mood": ["futuristic", "dystopian", "psychological"],
        "duration": 136,
        "rating": 8.7,
        "year": 1999,
    },
    {
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "genre": "Fantasy",
        "mood": ["epic", "adventure", "magical"],
        "duration": 178,
        "rating": 8.8,
        "year": 2001,
    },
    {
        "title": "Parasite",
        "genre": "Thriller",
        "mood": ["dark", "intense", "thought-provoking"],
        "duration": 132,
        "rating": 8.6,
        "year": 2019,
    },
    {
        "title": "La La Land",
        "genre": "Romance",
        "mood": ["romantic", "uplifting", "whimsical"],
        "duration": 128,
        "rating": 8.0,
        "year": 2016,
    },
    {
        "title": "Mad Max: Fury Road",
        "genre": "Action",
        "mood": ["intense", "thrilling", "adrenaline"],
        "duration": 120,
        "rating": 8.1,
        "year": 2015,
    },
    {
        "title": "Get Out",
        "genre": "Horror",
        "mood": ["suspenseful", "dark", "thought-provoking"],
        "duration": 104,
        "rating": 7.8,
        "year": 2017,
    },
    {
        "title": "Toy Story",
        "genre": "Animation",
        "mood": ["lighthearted", "heartwarming", "funny"],
        "duration": 81,
        "rating": 8.3,
        "year": 1995,
    },
    {
        "title": "The Social Network",
        "genre": "Drama",
        "mood": ["intense", "psychological", "contemplative"],
        "duration": 120,
        "rating": 7.8,
        "year": 2010,
    },
    {
        "title": "Knives Out",
        "genre": "Mystery",
        "mood": ["entertaining", "quirky", "suspenseful"],
        "duration": 130,
        "rating": 7.9,
        "year": 2019,
    },
    {
        "title": "Whiplash",
        "genre": "Drama",
        "mood": ["intense", "inspiring", "psychological"],
        "duration": 106,
        "rating": 8.5,
        "year": 2014,
    },
    {
        "title": "The Princess Bride",
        "genre": "Fantasy",
        "mood": ["adventure", "funny", "heartwarming"],
        "duration": 98,
        "rating": 8.0,
        "year": 1987,
    },
    {
        "title": "Joker",
        "genre": "Crime",
        "mood": ["dark", "psychological", "intense"],
        "duration": 122,
        "rating": 8.4,
        "year": 2019,
    },
    {
        "title": "Inside Out",
        "genre": "Animation",
        "mood": ["emotional", "heartwarming", "lighthearted"],
        "duration": 95,
        "rating": 8.1,
        "year": 2015,
    },
    {
        "title": "Dune",
        "genre": "Sci-Fi",
        "mood": ["epic", "futuristic", "contemplative"],
        "duration": 155,
        "rating": 8.0,
        "year": 2021,
    },
    {
        "title": "Hot Fuzz",
        "genre": "Comedy",
        "mood": ["funny", "entertaining", "thrilling"],
        "duration": 121,
        "rating": 7.8,
        "year": 2007,
    },
    {
        "title": "Arrival",
        "genre": "Sci-Fi",
        "mood": ["contemplative", "emotional", "mind-bending"],
        "duration": 116,
        "rating": 7.9,
        "year": 2016,
    },
    {
        "title": "The Silence of the Lambs",
        "genre": "Horror",
        "mood": ["suspenseful", "dark", "intense"],
        "duration": 118,
        "rating": 8.6,
        "year": 1991,
    },
    {
        "title": "Before Sunrise",
        "genre": "Romance",
        "mood": ["romantic", "contemplative", "lighthearted"],
        "duration": 101,
        "rating": 8.1,
        "year": 1995,
    },
    {
        "title": "Everything Everywhere All at Once",
        "genre": "Sci-Fi",
        "mood": ["mind-bending", "emotional", "entertaining"],
        "duration": 139,
        "rating": 7.8,
        "year": 2022,
    },
    {
        "title": "The Big Lebowski",
        "genre": "Comedy",
        "mood": ["quirky", "funny", "lighthearted"],
        "duration": 117,
        "rating": 8.1,
        "year": 1998,
    },
    {
        "title": "Interstellar",
        "genre": "Sci-Fi",
        "mood": ["epic", "emotional", "mind-bending"],
        "duration": 169,
        "rating": 8.7,
        "year": 2014,
    },
    {
        "title": "Amélie",
        "genre": "Romance",
        "mood": ["whimsical", "heartwarming", "quirky"],
        "duration": 122,
        "rating": 8.3,
        "year": 2001,
    },
    {
        "title": "John Wick",
        "genre": "Action",
        "mood": ["intense", "thrilling", "adrenaline"],
        "duration": 101,
        "rating": 7.4,
        "year": 2014,
    },
    {
        "title": "Hereditary",
        "genre": "Horror",
        "mood": ["dark", "suspenseful", "psychological"],
        "duration": 127,
        "rating": 7.3,
        "year": 2018,
    },
    {
        "title": "Paddington 2",
        "genre": "Comedy",
        "mood": ["heartwarming", "funny", "uplifting"],
        "duration": 103,
        "rating": 7.8,
        "year": 2017,
    },
    {
        "title": "Blade Runner 2049",
        "genre": "Sci-Fi",
        "mood": ["contemplative", "futuristic", "dystopian"],
        "duration": 164,
        "rating": 8.0,
        "year": 2017,
    },
    {
        "title": "Spider-Man: Into the Spider-Verse",
        "genre": "Animation",
        "mood": ["entertaining", "uplifting", "funny"],
        "duration": 117,
        "rating": 8.4,
        "year": 2018,
    },
    {
        "title": "No Country for Old Men",
        "genre": "Crime",
        "mood": ["dark", "suspenseful", "intense"],
        "duration": 122,
        "rating": 8.2,
        "year": 2007,
    },
    {
        "title": "The Grand Illusion",
        "genre": "Drama",
        "mood": ["contemplative", "emotional", "thought-provoking"],
        "duration": 114,
        "rating": 8.1,
        "year": 1937,
    },
    {
        "title": "Shaun of the Dead",
        "genre": "Comedy",
        "mood": ["funny", "entertaining", "quirky"],
        "duration": 99,
        "rating": 7.9,
        "year": 2004,
    },
    {
        "title": "Pan's Labyrinth",
        "genre": "Fantasy",
        "mood": ["dark", "magical", "emotional"],
        "duration": 118,
        "rating": 8.2,
        "year": 2006,
    },
    {
        "title": "The Departed",
        "genre": "Crime",
        "mood": ["intense", "suspenseful", "dark"],
        "duration": 151,
        "rating": 8.5,
        "year": 2006,
    },
    {
        "title": "Coco",
        "genre": "Animation",
        "mood": ["emotional", "heartwarming", "magical"],
        "duration": 105,
        "rating": 8.4,
        "year": 2017,
    },
    {
        "title": "The Witch",
        "genre": "Horror",
        "mood": ["dark", "suspenseful", "psychological"],
        "duration": 92,
        "rating": 6.9,
        "year": 2015,
    },
    {
        "title": "Mission: Impossible – Fallout",
        "genre": "Action",
        "mood": ["thrilling", "adrenaline", "entertaining"],
        "duration": 147,
        "rating": 7.7,
        "year": 2018,
    },
    {
        "title": "Little Women",
        "genre": "Drama",
        "mood": ["heartwarming", "emotional", "inspiring"],
        "duration": 135,
        "rating": 7.8,
        "year": 2019,
    },
    {
        "title": "The Nice Guys",
        "genre": "Comedy",
        "mood": ["funny", "entertaining", "quirky"],
        "duration": 116,
        "rating": 7.4,
        "year": 2016,
    },
    {
        "title": "Ex Machina",
        "genre": "Sci-Fi",
        "mood": ["psychological", "mind-bending", "suspenseful"],
        "duration": 108,
        "rating": 7.7,
        "year": 2014,
    },
    {
        "title": "Pride & Prejudice",
        "genre": "Romance",
        "mood": ["romantic", "heartwarming", "lighthearted"],
        "duration": 129,
        "rating": 7.8,
        "year": 2005,
    },
    {
        "title": "The Raid",
        "genre": "Action",
        "mood": ["intense", "adrenaline", "thrilling"],
        "duration": 101,
        "rating": 7.6,
        "year": 2011,
    },
    {
        "title": "Moonlight",
        "genre": "Drama",
        "mood": ["emotional", "contemplative", "thought-provoking"],
        "duration": 111,
        "rating": 7.4,
        "year": 2016,
    },
    {
        "title": "A Quiet Place",
        "genre": "Horror",
        "mood": ["suspenseful", "intense", "emotional"],
        "duration": 90,
        "rating": 7.5,
        "year": 2018,
    },
    {
        "title": "Guardians of the Galaxy",
        "genre": "Action",
        "mood": ["funny", "entertaining", "uplifting"],
        "duration": 121,
        "rating": 8.0,
        "year": 2014,
    },
    {
        "title": "The Truman Show",
        "genre": "Drama",
        "mood": ["thought-provoking", "quirky", "emotional"],
        "duration": 103,
        "rating": 8.2,
        "year": 1998,
    },
    {
        "title": "Howl's Moving Castle",
        "genre": "Animation",
        "mood": ["magical", "enchanting", "romantic"],
        "duration": 119,
        "rating": 8.2,
        "year": 2004,
    },
    {
        "title": "Gone Girl",
        "genre": "Thriller",
        "mood": ["suspenseful", "dark", "psychological"],
        "duration": 149,
        "rating": 8.1,
        "year": 2014,
    },
    {
        "title": "The Farewell",
        "genre": "Drama",
        "mood": ["emotional", "heartwarming", "contemplative"],
        "duration": 100,
        "rating": 7.5,
        "year": 2019,
    },
    {
        "title": "Baby Driver",
        "genre": "Action",
        "mood": ["entertaining", "thrilling", "funny"],
        "duration": 113,
        "rating": 7.6,
        "year": 2017,
    },
    {
        "title": "Eternal Sunshine of the Spotless Mind",
        "genre": "Romance",
        "mood": ["romantic", "mind-bending", "emotional"],
        "duration": 108,
        "rating": 8.3,
        "year": 2004,
    },
    {
        "title": "Train to Busan",
        "genre": "Horror",
        "mood": ["intense", "thrilling", "emotional"],
        "duration": 118,
        "rating": 7.6,
        "year": 2016,
    },
    {
        "title": "The Lego Movie",
        "genre": "Animation",
        "mood": ["funny", "lighthearted", "uplifting"],
        "duration": 100,
        "rating": 7.7,
        "year": 2014,
    },
    {
        "title": "Sicario",
        "genre": "Thriller",
        "mood": ["intense", "dark", "suspenseful"],
        "duration": 121,
        "rating": 7.7,
        "year": 2015,
    },
    {
        "title": "About Time",
        "genre": "Romance",
        "mood": ["romantic", "heartwarming", "funny"],
        "duration": 123,
        "rating": 7.8,
        "year": 2013,
    },
    {
        "title": "Edge of Tomorrow",
        "genre": "Sci-Fi",
        "mood": ["thrilling", "entertaining", "adrenaline"],
        "duration": 113,
        "rating": 7.9,
        "year": 2014,
    },
    {
        "title": "The Hunt",
        "genre": "Drama",
        "mood": ["intense", "thought-provoking", "emotional"],
        "duration": 115,
        "rating": 8.3,
        "year": 2012,
    },
    {
        "title": "Zootopia",
        "genre": "Animation",
        "mood": ["funny", "entertaining", "thought-provoking"],
        "duration": 108,
        "rating": 8.0,
        "year": 2016,
    },
    {
        "title": "Prisoners",
        "genre": "Thriller",
        "mood": ["dark", "suspenseful", "intense"],
        "duration": 153,
        "rating": 8.1,
        "year": 2013,
    },
    {
        "title": "Superbad",
        "genre": "Comedy",
        "mood": ["funny", "lighthearted", "entertaining"],
        "duration": 113,
        "rating": 7.6,
        "year": 2007,
    },
    {
        "title": "The Green Knight",
        "genre": "Fantasy",
        "mood": ["contemplative", "magical", "dark"],
        "duration": 130,
        "rating": 6.6,
        "year": 2021,
    },
    {
        "title": "Nightcrawler",
        "genre": "Crime",
        "mood": ["dark", "psychological", "intense"],
        "duration": 117,
        "rating": 7.8,
        "year": 2014,
    },
    {
        "title": "Ratatouille",
        "genre": "Animation",
        "mood": ["heartwarming", "inspiring", "funny"],
        "duration": 111,
        "rating": 8.1,
        "year": 2007,
    },
]
